spring:
  datasource:
    url: jdbc:h2:mem:shopdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # 개발 단계: create / update / create-drop 중 골라서 사용
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": false # 로그는 위 logging.level로 제어
    open-in-view: false # 실전 패턴에 맞게 미리 끄는 걸 추천

  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    type: caffeine
    cache-names: members, products, orders
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, httptrace # httptrace는 별도 설정 필요할 수 있음
  endpoint:
    health:
      show-details: when_authorized
